import RPi.GPIO as GPIO
import time


GPIO.setmode(GPIO.BOARD)
LED1 = 37
LED2 = 35
LED3 = 33
LED4 = 31
LED5 = 29
ON = 1
OFF = 0

GPIO.setup(LED1, GPIO.OUT)
GPIO.setup(LED2, GPIO.OUT)
GPIO.setup(LED3, GPIO.OUT)
GPIO.setup(LED4, GPIO.OUT)
GPIO.setup(LED5, GPIO.OUT)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.OFF)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.OFF)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.OFF)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.OFF)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.OFF)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.setup(LED1, GPIO.ON)
GPIO.setup(LED2, GPIO.ON)
GPIO.setup(LED3, GPIO.ON)
GPIO.setup(LED4, GPIO.ON)
GPIO.setup(LED5, GPIO.ON)
time.sleep(0.8)

GPIO.cleanup()
